services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: next-portfolio:latest
    container_name: next-portfolio
    environment:
      - NODE_ENV=production
      - PORT=3004
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "127.0.0.1:3004:3004"
    restart: unless-stopped
